const checklistTemplates = [
  {
    id: "travel-medicine",
    name: "常用药品与急救",
    recommendedScope: "我的",
    symbol: "药",
    description: "按个人健康情况增减；处方药和用药信息建议本人保管。",
    items: [
      { title: "个人处方药与备用量", key: true },
      { title: "用药清单、处方与过敏信息", key: true },
      { title: "创可贴、无菌纱布与医用胶带" },
      { title: "消毒湿巾或消毒用品" },
      { title: "退热止痛药" },
      { title: "抗过敏药" },
      { title: "晕车药" },
      { title: "肠胃药与口服补液盐" },
    ],
  },
  {
    id: "travel-documents",
    name: "证件与资料",
    recommendedScope: "我的",
    symbol: "证",
    description: "集中核对本人证件、车辆资料和已确认的订单信息。",
    items: [
      { title: "身份证", key: true },
      { title: "驾驶证（驾驶人）", key: true },
      { title: "机动车行驶证", key: true },
      { title: "车辆保险或电子保单" },
      { title: "酒店与票务订单" },
      { title: "紧急联系人与重要电话" },
    ],
  },
  {
    id: "vehicle-check",
    name: "车辆出发检查",
    recommendedScope: "公共",
    symbol: "车",
    description: "出发前集中检查影响行车安全和续航的关键项目。",
    items: [
      { title: "轮胎胎压、磨损与备胎", key: true },
      { title: "机油、冷却液、制动液与玻璃水", key: true },
      { title: "蓄电池与充电系统" },
      { title: "前灯、刹车灯、转向灯与双闪", key: true },
      { title: "雨刷与挡风玻璃" },
      { title: "制动系统与异常声响" },
      { title: "油量或剩余电量与补能计划" },
    ],
  },
  {
    id: "home-safety",
    name: "离家安全检查",
    recommendedScope: "公共",
    symbol: "家",
    description: "离家前逐项确认燃气、电源、门窗和生活安排。",
    items: [
      { title: "关闭燃气阀门", key: true },
      { title: "关闭不必要的电器与电源", key: true },
      { title: "关好门窗并锁门", key: true },
      { title: "清理厨房、阳台和楼道可燃杂物" },
      { title: "倒垃圾并处理易腐食物" },
      { title: "安排宠物、绿植与备用钥匙" },
      { title: "暂停或委托代收快递" },
    ],
  },
  {
    id: "road-emergency",
    name: "车载应急物资",
    recommendedScope: "公共",
    symbol: "援",
    description: "覆盖途中故障、夜间停车和临时滞留时常用的基础物资。",
    items: [
      { title: "手机、车充与充电宝", key: true },
      { title: "急救包", key: true },
      { title: "反光背心与三角警告牌", key: true },
      { title: "手电筒与备用电池" },
      { title: "搭电线或应急启动电源" },
      { title: "千斤顶、备胎与补胎工具" },
      { title: "饮用水与耐储存食物" },
      { title: "纸质或离线地图与紧急电话" },
    ],
  },
  {
    id: "road-trip-comfort",
    name: "车内舒适与卫生",
    recommendedScope: "公共",
    symbol: "舒",
    description: "减少长途驾驶中的杂乱、口渴和临时清洁问题，按人数和天气增减。",
    items: [
      { title: "饮用水与可重复使用水杯", key: true },
      { title: "纸巾、湿巾与免洗洗手液" },
      { title: "垃圾袋与密封袋" },
      { title: "耐储存零食" },
      { title: "遮阳挡或车窗遮光用品" },
      { title: "颈枕、眼罩或耳塞" },
      { title: "车内清洁布与小型清洁用品" },
      { title: "备用眼镜或隐形眼镜用品" },
    ],
  },
  {
    id: "electronics-navigation",
    name: "电子设备与导航",
    recommendedScope: "我的",
    symbol: "电",
    description: "集中检查充电、导航和重要文件备份，避免途中找不到或没电。",
    items: [
      { title: "手机与备用手机", key: true },
      { title: "各设备充电线与充电头", key: true },
      { title: "车载充电器或点烟器转换头" },
      { title: "充电宝并确认电量" },
      { title: "下载离线地图与目的地资料" },
      { title: "相机、存储卡与备用电池" },
      { title: "重要订单和证件照片备份" },
      { title: "耳机、手表等个人设备" },
    ],
  },
  {
    id: "clothing-toiletries",
    name: "衣物与洗漱用品",
    recommendedScope: "我的",
    symbol: "衣",
    description: "按天气、住宿条件和天数准备，雨具、防晒和换洗衣物单独核对。",
    items: [
      { title: "换洗衣物与内衣袜", key: true },
      { title: "洗漱用品与毛巾" },
      { title: "拖鞋或轻便鞋" },
      { title: "外套、保暖层或防晒衣" },
      { title: "雨衣或折叠雨伞" },
      { title: "防晒霜、太阳镜与帽子" },
      { title: "驱蚊用品" },
      { title: "脏衣袋与备用鞋袋" },
    ],
  },
  {
    id: "lodging-checkin",
    name: "住宿入住检查",
    recommendedScope: "公共",
    symbol: "住",
    description: "出发前和办理入住时核对地址、停车、入住须知与随身物品。",
    items: [
      { title: "核对酒店地址、电话与入住时间", key: true },
      { title: "确认停车入口、收费和限高信息" },
      { title: "保存酒店订单与前台联系方式" },
      { title: "确认同行人的房间和入住安排" },
      { title: "入住时检查门锁、窗户和贵重物品存放" },
      { title: "退房前检查充电器、证件和房间物品", key: true },
    ],
  },
  {
    id: "camping-outdoor",
    name: "露营与户外装备",
    recommendedScope: "公共",
    symbol: "野",
    description: "仅在确定露营或户外活动时导入；营地、天气和防火要求要提前确认。",
    items: [
      { title: "帐篷、防雨罩与地钉", key: true },
      { title: "睡袋、睡垫与保暖层", key: true },
      { title: "头灯或手电筒与备用电池" },
      { title: "饮用水、食品与密封收纳袋" },
      { title: "炉具、燃料、锅具与餐具" },
      { title: "折叠椅、桌布或防潮垫" },
      { title: "绳索、多功能工具与简单修补用品" },
      { title: "垃圾袋、急救包与防虫用品" },
    ],
  },
  {
    id: "family-travel",
    name: "亲子出行",
    recommendedScope: "我的",
    symbol: "亲",
    description: "按孩子年龄和健康情况调整；儿童安全座椅与常用物品优先确认。",
    items: [
      { title: "儿童身份证件与就医信息", key: true },
      { title: "适龄儿童安全座椅", key: true },
      { title: "备用衣物、围兜与防水袋" },
      { title: "纸尿裤、湿巾或护理用品" },
      { title: "儿童常用药与体温计" },
      { title: "饮水、零食与便携餐具" },
      { title: "安抚物品、绘本或车内娱乐" },
      { title: "防晒、遮雨和防蚊用品" },
    ],
  },
  {
    id: "pet-travel",
    name: "宠物同行",
    recommendedScope: "我的",
    symbol: "宠",
    description: "确认目的地和住宿允许宠物，并让宠物在车内始终保持安全固定。",
    items: [
      { title: "宠物航空箱或车载安全带", key: true },
      { title: "牵引绳、胸背和身份牌", key: true },
      { title: "宠物粮、水、碗与零食" },
      { title: "疫苗、驱虫和宠物医疗信息" },
      { title: "常用药、晕车处理和兽医电话" },
      { title: "尿垫、拾便袋与清洁湿巾" },
      { title: "宠物熟悉的毯子或安抚物" },
      { title: "备用毛巾和换洗用品" },
    ],
  },
  {
    id: "long-drive-safety",
    name: "长途驾驶安全确认",
    recommendedScope: "公共",
    symbol: "安",
    description: "出发前确认天气、路况、休息和补能安排，途中避免疲劳驾驶。",
    items: [
      { title: "查看天气、路况和施工提醒", key: true },
      { title: "规划休息点与驾驶人轮换" },
      { title: "确认油量或电量、补能点和备用方案", key: true },
      { title: "确认所有乘员系好安全带" },
      { title: "保存道路救援和保险电话" },
      { title: "向家人或朋友告知大致行程" },
      { title: "检查儿童、宠物和行李固定情况" },
    ],
  },
];

const getChecklistTemplate = (templateId) =>
  checklistTemplates.find((template) => template.id === templateId);

module.exports = { checklistTemplates, getChecklistTemplate };
